export class Cart{
    CART_ID:string;
    USER_ID:string;
    PRODUCT_ID:string;
    PRODUCT_NAME:string;
    PRODUCT_TYPE:string;
    PRODUCT_PRICE:number;
    PRODUCT_INFO:string;
    PRODUCT_RATING:number;
    PRODUCT_TOTAL:number;
    PRODUCT_IMAGE:string;
    SKINTYPE_NAME:String;
    PRODUCT_ORIGIN:string;
    PRODUCT_BRAND:string;
    PRODUCT_CAPACITY:string;
    PRODUCT_AMOUNT:number;

    constructor(){
        this.CART_ID=null;
        this.USER_ID=null;
        this.PRODUCT_ID=null;
        this.PRODUCT_NAME=null;
        this.PRODUCT_TYPE=null;
        this.PRODUCT_PRICE=null;
        this.PRODUCT_INFO=null;
        this.PRODUCT_RATING=null;
        this.PRODUCT_TOTAL=null;
        this.PRODUCT_IMAGE=null;
        this.SKINTYPE_NAME=null;
        this.PRODUCT_ORIGIN=null;
        this.PRODUCT_BRAND=null;
        this.PRODUCT_CAPACITY=null;
        this.PRODUCT_AMOUNT=null;
    }
}